version: '3.9'

services:
  app:
    build: ./
    image: chatroom-backend-image:latest
    container_name: chatroom-backend-app
    restart: always
    networks:
      - intranet
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file:
      - ".env"
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-backend-app
    restart: always
    networks:
      - intranet
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
  db:
    image: postgres:15
    container_name: postgres-backend-app
    restart: always
    networks:
      - intranet
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ".env"


networks:
  intranet:
    driver: bridge

volumes:
  ollama:
    external: true
    name: ollama
  postgres_data:
  